shutdown_costmaps: false

controller_frequency: 20
controller_patience: 15

planner_frequency: 20
planner_patience: 15

oscillation_timeout: 5
oscillation_distance: 0.0

recovery_behavior_enabled: false
clearing_rotation_allowed: false